src: cpu: conv: Use acl_indirect_gemm for bf16 convolutions
oneapi-src/oneDNN pull request #1933
Opened 2024-05-28 10:52 UTC by Ryo-not-rio

# Description
performance improvements:

Total benchdnn tests: 57
Min: 15x
Average: 131x
Max: 320x

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

## Performance improvements

- [x] Have you submitted performance data that demonstrates performance improvements?

2024-05-28 16:36 UTC, dzarukin approved these changes

2024-06-04 13:06 UTC, jondea approved these changes
Reviewed internally, LGTM

2024-06-06 10:10 UTC, jondea requested changes
We need to amend the indirect/gemm heuristics to take into account bf16*bf16->bf16. Currently they only consider fast math.

2024-06-06 18:21 UTC, jondea commented
> We need to amend the indirect/gemm heuristics to take into account bf16*bf16->bf16. Currently they only consider fast math.

This has been fixed by #1948

2024-06-06 18:21 UTC, jondea approved these changes

2024-06-24 15:35 UTC, merged