cpu::aarch64:: Enable BRGEMM Depthwise Forward Convolution.
oneapi-src/oneDNN pull request #2009
Opened 2024-07-26 11:08 UTC by kasturedeeksha

# Description

This commit enables BRGEMM depthwise forward convolution for the ARM SVE ISA.
Major code changes:

- Added BRGEMM depthwise convolution files in src/aarch64 to support BRGEMM depthwise forward convolution.
- Updated brgemm_utils.cpp and brgemm.cpp to support multiple ISAs by incorporating relevant changes.

# Checklist

## General

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit? Yes
1. make test output: 
```
99% tests passed, 2 tests failed out of 196

Total Test time (real) = 1461.70 sec

The following tests FAILED:
        155 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
        177 - test_benchdnn_modeC_graph_ci_cpu (Failed)
Errors while running CTest
Output from these tests are in: /home/deekshak/xybak/oss_pr/latest_brgemm/oneDNN_Fork/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
```
- [x] Have you formatted the code using clang-format? Yes

cc : @kawakami-k

2024-08-05 15:46 UTC, abhijain1204fujitsu commented
@vpirogov , kindly share your feedback on this PR and support for merger

2024-08-06 17:01 UTC, vpirogov commented
@oneapi-src/onednn-cpu-aarch64, @snadampal, @kawakami-k, could you please help reviewing and validating this one?

2024-08-08 09:30 UTC, mgouicem approved these changes

2024-08-08 12:03 UTC, jondea requested changes
Thanks for the contribution, we really appreciate your work on sve 256.

I don't have any comments on the xbyak_aarch64 code, I'm not familiar enough with it to be useful, but otherwise it looks good.

What inputs have you been testing this on? I tried it with `test_conv_depthwise` and didn't get any hits because there was no `--dir=FWD_I`. Would you be able to add a benchdnn input file which trigger these code paths please?

Also, how have you tested the sve 256 code paths?

2024-08-08 12:09 UTC, jondea commented
Also, out of curiosity, what's the feature/performance difference between this and the jit depthwise backend (like in #2014)? As in, why do we have both?

2024-08-08 14:26 UTC, snadampal commented
Hi @kasturedeeksha , same comment as Jonathan, please share details on (1) why and where is this feature important? (2) what scenarios have been tested and was the improvement observed?

I believe you tested sve 256 on AWS Graviton3. how about sve 128 support?

2024-08-12 06:20 UTC, kasturedeeksha commented
@jondea @snadampal 
BRGEMM Depthwise supports the **NHWC** format, so when running tests, we need to set the options `--stag` and `--dtag`. There is an input file on which I tested, specifically `set_conv_dw`. The command used was:
 
```
./benchdnn --conv --dt=f32 --stag=axb --dtag=axb --batch=inputs/conv/set_conv_dw
```
For above I tested for --dir = FWD_I, FWD_D and FWD_B
For overall testing of convolution, I also tested with `test_conv_all`.
When testing with `test_conv_depthwise`, 4291 tests were executed using the BRGEMM SVE256 path.

2024-08-12 06:21 UTC, kasturedeeksha commented
@jondea @snadampal 
This feature is important because it optimizes depthwise convolution for Arm and enables 3D convolution, resulting in a substantial performance boost.
Regarding the difference between the two PRs: The implementation in https://github.com/oneapi-src/oneDNN/pull/2014 supports both forward and backward depthwise convolution in the NCHW memory format, while the implementation in this PR supports forward depthwise convolution in the NHWC memory format.
Finally, expansion for SVE128 is planned as a future work.

2024-08-15 10:21 UTC, jondea approved these changes
Great, thank you for your work and the detailed response.

2024-08-16 03:13 UTC, abhijain1204fujitsu commented
@vpirogov, @mgouicem , as the changes are approved. Kindly support us to merge these changes.

2024-08-16 15:58 UTC, vpirogov commented
@kasturedeeksha, there are few more things to address on this PR:
* Merge commits are not allowed in main branch. Please rebase your changes.
* Commits messages should be formatted according to [code contribution guidelines](https://github.com/oneapi-src/oneDNN/blob/main/CONTRIBUTING.md#code-contribution-guidelines)

2024-08-20 11:30 UTC, kasturedeeksha commented
@vpirogov @mgouicem 
I’ve rebased the PR and updated the commit messages as per the guidelines.
Please review the changes and support us to merge.

2024-08-20 23:43 UTC, merged