cpu: aarch64 make binary ops use stateless ACL interface
oneapi-src/oneDNN pull request #2049
Opened 2024-08-21 16:59 UTC by Sqvid

# Description
make binary ops use stateless ACL interface
> [!NOTE]
> This patch depends on ACL v23.08.1. Please add it to the 3.6 milestone but kindly wait for the ACL v23.08.1 release before merging.

Will allow all post-ops to be made stateless, as pointed out by @dzarukin in [this comment](https://github.com/oneapi-src/oneDNN/pull/2043#discussion_r1723733268).

# Checklist
## General
- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally for each commit?
- [x] Have you formatted the code using clang-format?

2024-08-22 08:12 UTC, jondea requested changes
Generally looks good, thank you, I just have a few minor comments. I know that this has been reviewed internally by others too.

If this patch requires 24.08.1, can we bump the minimum required version in this patch? Even if it doesn't exist yet

2024-08-22 15:58 UTC, deb-intel reviewed
readme file LGTM

2024-08-28 14:38 UTC, Sqvid commented
@vpirogov ACL v24.08.1 has been released today and this patch passes our internal CI. It is good to merge.

2024-08-28 15:05 UTC, mgouicem approved these changes

2024-08-28 15:33 UTC, merged