gpu: generic: sycl: lnorm: Intel GPU precision issues
oneapi-src/oneDNN pull request #2071
Opened 2024-09-02 13:46 UTC by kala855

# Description

When used in Intel PVC, the layer normalization SYCL kernel implementation faces some precision issues in variance computation.

```bash
create: --lnorm --engine=gpu --inplace=true 30x300
run: --lnorm --engine=gpu --inplace=true 30x300
[   0][VAR][0] exp_f32:   0.0202823 exp:   0.0202823 got:   0.0202823 diff:1.86265e-09 rdiff:9.1836e-08
[   1][VAR][1] exp_f32:   0.0804944 exp:   0.0804944 got:   0.0804944 diff:7.45058e-09 rdiff:9.25603e-08
[   2][VAR][2] exp_f32:    0.327062 exp:    0.327062 got:    0.327062 diff:2.98023e-08 rdiff:9.11213e-08
[   6][VAR][6] exp_f32:     82.4779 exp:     82.4779 got:     82.4779 diff:7.62939e-06 rdiff:9.25023e-08
[  17][VAR][17] exp_f32:      1.3052 exp:      1.3052 got:      1.3052 diff:1.19209e-07 rdiff:9.1334e-08
[  22][VAR][22] exp_f32:   0.0829537 exp:   0.0829537 got:   0.0829537 diff:7.45058e-09 rdiff:8.98161e-08
[  23][VAR][23] exp_f32:    0.324289 exp:    0.324289 got:    0.324289 diff:2.98023e-08 rdiff:9.19006e-08
[  29][VAR][29] exp_f32:   0.0822034 exp:   0.0822034 got:   0.0822034 diff:7.45058e-09 rdiff:9.0636e-08
[COMPARE_STATS][VAR]: trh=0 err_max_diff:7.62939e-06 err_max_rdiff:9.25603e-08 all_max_diff:7.62939e-06 all_max_rdiff:9.25603e-08
0:FAILED (errors:8 total:9060) __REPRO: --lnorm --engine=gpu --inplace=true 30x300
```

```bash
[  14][VAR][14] exp_f32: 2.68618e-05 exp: 2.68618e-05 got: 2.68618e-05 diff:1.81899e-12 rdiff:6.77165e-08
[COMPARE_STATS][VAR]: trh=0 err_max_diff:1.81899e-12 err_max_rdiff:6.77165e-08 all_max_diff:1.81899e-12 all_max_rdiff:6.77165e-08
8471:FAILED (errors:1 total:75) __REPRO: --lnorm --engine=gpu --dt=f32:bf16 --tag=axb --stat_tag=abx --flags=CH 15x3_n"lnorm_ci_0d:0"
```

The previous are just a couple of failing examples.

As a proposal, the variance threshold is modified to pass the failing tests.

2024-09-02 13:55 UTC, kala855 commented
To give a little bit of additional context. I found that in this [line](https://github.com/oneapi-src/oneDNN/blob/08fd0eee29cc523ae0f4905c148513c43e7e948d/src/gpu/generic/sycl/layer_normalizations_kernels.hpp#L218). The division is making **v_variance** slightly different from the reference that is computed in benchdnn (there is a thr=0 for these cases). Maybe that is happening because of some compiler optimization.

2024-09-03 07:25 UTC, t4c1 approved these changes
Looks like an improvement. However I would just set the threshold to 5e-7 for all the cases, as 0 does not make sense as soon as floating point calculations are involved.

2024-09-03 08:40 UTC, sgeor255 approved these changes

2024-09-03 10:16 UTC, mgouicem commented
Do you know what is the default setting for `fp_config::correctly_rounded_divide_sqrt` on this device?
We typically [disable `fast-reciprocal`](https://github.com/oneapi-src/oneDNN/blob/3292be76f68cf7544cff1c1e75c78f1a00fe90f1/cmake/platform.cmake#L215-L217), I wonder if we should do something similar for sycl kernels

2024-09-03 16:37 UTC, vpirogov commented
@kala855, benchdnn is very sensitive to numerical issues by design. So in cases like this it's important to understand where the difference is coming from before considering the threshold change.

2024-09-13 08:10 UTC, kala855 commented
> Do you know what is the default setting for `fp_config::correctly_rounded_divide_sqrt` on this device? We typically [disable `fast-reciprocal`](https://github.com/oneapi-src/oneDNN/blob/3292be76f68cf7544cff1c1e75c78f1a00fe90f1/cmake/platform.cmake#L215-L217), I wonder if we should do something similar for sycl kernels

We have been checking carefully these days to see what is happening here. Doing a comparison between the assembly generated by **icpx** on the OCL and SYCL versions of the implementations we found that:

1. The OCL version generates an instruction **math.invm** which is IEEE standard compliant and is used to compute the division.
2. The SYCL version generates an instruction **math.inv** which is not IEEE standard compliant and is the instruction that generates the precision issues.
3. We were looking at different compiler flags to try to generate the same behavior on the SYCL side but was not possible.
4. We are thinking that the problem is due to some compiler bug that does not take into account the flags to generate the expected code. (-fno-fast-math, -ffp-model=precise, etc.)
5. Info about **math.inv** and **math.invm** instructions could be found [here ](https://cdrdv2.intel.com/v1/dl/getcontent/682682) pages 24 and 26 respectively.

Any suggestions or feedback will be more than welcome. Thanks.

@mgouicem @t4c1 @sgeor255

2024-09-16 08:41 UTC, mgouicem commented
Thanks for checking.  I would suggest:
- to open an issue against the sycl compiler with your findings, 
- add a condition on that threshold increase on `DNNL_WITH_SYCL`
- add a comment to your patch so that we can revert the threshold as the issue is resolved on sycl compiler side.

2024-09-30 11:20 UTC, kala855 commented
> Thanks for checking. I would suggest:
> 
> * to open an issue against the sycl compiler with your findings,
> * add a condition on that threshold increase on `DNNL_WITH_SYCL`
> * add a comment to your patch so that we can revert the threshold as the issue is resolved on sycl compiler side.

Hi @mgouicem I did what you mentioned to try to get the SYCL **lnorm** benchdnn tests working. The issue was opened and a workaround was pushed in this PR. Thanks for your feedback.

2024-10-04 08:33 UTC, t4c1 approved these changes
LGTM, but I still believe it would be better to have nonzero threshold for all cases.

2024-10-04 08:43 UTC, mgouicem approved these changes

2024-10-09 13:53 UTC, kala855 commented
We found that `SYCL_PROGRAM_COMPILE_OPTIONS="-cl-fp32-correctly-rounded-divide-sqrt"` environment variable strengthens the requirements for floating-point division, making it correctly-rounded. I made some changes to set the variable and unset it just in the operators that need it. Batch normalization was failing because of the same issue. The last commit also fixes the problem in bnorm.

2024-10-10 07:52 UTC, t4c1 reviewed
LGTM. Maybe we could mention in the comment before the option that this is specifically required for Intel devices.

2024-10-10 07:56 UTC, mgouicem commented on src/gpu/generic/sycl/ref_batch_normalization.cpp
> +        setenv("SYCL_PROGRAM_COMPILE_OPTIONS",
I believe this is not thread-safe to use setenv (e.g. another concurrent call to the same primitive might unset it after this one sets it).

2024-10-10 07:56 UTC, mgouicem commented on src/gpu/generic/sycl/ref_batch_normalization.cpp
> +        unsetenv("SYCL_PROGRAM_COMPILE_OPTIONS");
Also, here it does not restore the env var to its original value.

2024-10-10 07:58 UTC, mgouicem commented
> We found that `SYCL_PROGRAM_COMPILE_OPTIONS="-cl-fp32-correctly-rounded-divide-sqrt"` environment variable strengthens the requirements for floating-point division, making it correctly-rounded. I made some changes to set the variable and unset it just in the operators that need it. Batch normalization was failing because of the same issue. The last commit also fixes the problem in bnorm.

Is there a programmatic way to control the same knob (that does not involve envvar)? It is typically not thread-safe to modify environment variables and this should be avoided as much as possible IMHO.

2024-10-10 15:29 UTC, dzarukin commented on tests/benchdnn/lnorm/lnorm.cpp
> +#else
Is this still needed with the new option given to the kernel?

2024-10-23 13:42 UTC, mgouicem requested changes
Current PR relies on non thread-safe environment variable setting.

2025-01-03 23:54 UTC, vpirogov commented
Closing as stale.

2025-01-03 23:54 UTC, closed without merging