src: cpu: aarch64: injectors: eltwise_injector - improve gelu performance for block size 16
oneapi-src/oneDNN pull request #2072
Opened 2024-09-03 10:15 UTC by nikhilfujitsu

# Description

Improvement: gelu performance for block size 16 in jit_uni_eltwise_injector
This commit improves the performance of gelu function jit_uni_eltwise_injector for block size 16:
## Major Code changes:
• Added a new function gelu_erf_minimax_approx_compute_vector_fwd(const TRegS &vmm_src) for
computing gelu_erf for block size 16.
• Added new gelu_minimax constants and polynomial constants table.
Checklist
## General
[✓] Do all unit and benchdnn tests (make test and make test_benchdnn_*) pass locally for each commit? Yes
Test output is same with and without this commit.
make test summary :

81% tests passed, 38 tests failed out of 199
 
Total Test time (real) = 3772.04 sec
 
The following tests FAILED:
         48 - api-c (Failed)
         54 - test_convolution_backward_data_f32 (Subprocess aborted)
         87 - test_reorder (Failed)
        122 - test_graph_c_api_compile_parametrized_usm_cpu (Failed)
        151 - test_graph_unit_dnnl_concat_usm_cpu (Failed)
        152 - test_graph_unit_dnnl_conv_usm_cpu (Failed)
        153 - test_graph_unit_dnnl_convtranspose_usm_cpu (Failed)
        156 - test_graph_unit_dnnl_group_norm_usm_cpu (Failed)
        158 - test_graph_unit_dnnl_large_partition_usm_cpu (Failed)
        159 - test_graph_unit_dnnl_layer_norm_usm_cpu (Failed)
        160 - test_graph_unit_dnnl_matmul_usm_cpu (Failed)
        161 - test_graph_unit_dnnl_mqa_decomp_usm_cpu (Failed)
        162 - test_graph_unit_dnnl_pool_usm_cpu (Failed)
        167 - test_graph_unit_dnnl_sdp_decomp_usm_cpu (Failed)
        168 - test_graph_unit_dnnl_softmax_usm_cpu (Failed)
        173 - test_benchdnn_modeC_bnorm_ci_cpu (Failed)
        175 - test_benchdnn_modeC_concat_ci_cpu (Failed)
        176 - test_benchdnn_modeC_conv_ci_cpu (Failed)
        177 - test_benchdnn_modeC_deconv_ci_cpu (Failed)
        178 - test_benchdnn_modeC_eltwise_ci_cpu (Failed)
        179 - test_benchdnn_modeC_gnorm_ci_cpu (Failed)
        180 - test_benchdnn_modeC_graph_ci_cpu (Failed)
        181 - test_benchdnn_modeC_ip_ci_cpu (Failed)
        183 - test_benchdnn_modeC_lrn_ci_cpu (Failed)
        184 - test_benchdnn_modeC_matmul_ci_cpu (Failed)
        185 - test_benchdnn_modeC_pool_ci_cpu (Failed)
        186 - test_benchdnn_modeC_prelu_ci_cpu (Failed)
        187 - test_benchdnn_modeC_reduction_ci_cpu (Failed)
        188 - test_benchdnn_modeC_reorder_ci_cpu (Failed)
        189 - test_benchdnn_modeC_resampling_ci_cpu (Failed)
        190 - test_benchdnn_modeC_augru_ci_cpu (Failed)
        191 - test_benchdnn_modeC_gru_ci_cpu (Failed)
        192 - test_benchdnn_modeC_lstm_ci_cpu (Failed)
        193 - test_benchdnn_modeC_rnn_ci_cpu (Failed)
        194 - test_benchdnn_modeC_self_ci_cpu (Failed)
        195 - test_benchdnn_modeC_shuffle_ci_cpu (Failed)
        196 - test_benchdnn_modeC_softmax_ci_cpu (Failed)
        197 - test_benchdnn_modeC_sum_ci_cpu (Failed)
Errors while running CTest
Output from these tests are in: /home/nikhil/oneDNN/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [Makefile:71: test] Error 8
[✓] Have you formatted the code using clang-format? Yes

2024-09-05 10:37 UTC, abhijain1204fujitsu commented
@vpirogov , @jondea , Kindly support to review the PR

2024-09-06 13:00 UTC, jondea commented
Do you have any specific `benchdnn` calls which will exercise this path?

2024-09-06 14:13 UTC, jondea commented
Also, I'm not seeing the same failures on this patch (or before) as you. E.g., out of the CI failures, I can only see `test_benchdnn_modeC_graph_ci_cpu`. Would you be able to investigate this please?

Also, do you have any measurements of the speedup of this optimization?

2024-09-09 05:01 UTC, nikhilfujitsu commented
> Do you have any specific `benchdnn` calls which will exercise this path?

Hi, please checkout these log, the machine is A64FX and uses jit_sve_512.
[A64_FX_benchdnn_eltwise_gelu.log](https://github.com/user-attachments/files/16925569/A64_FX_benchdnn_eltwise_gelu.log)
[A64_FX_benchdnn_VERBOSE_eltwise_gelu.log](https://github.com/user-attachments/files/16925570/A64_FX_benchdnn_VERBOSE_eltwise_gelu.log)

2024-09-09 05:14 UTC, nikhilfujitsu commented
> Also, I'm not seeing the same failures on this patch (or before) as you. E.g., out of the CI failures, I can only see `test_benchdnn_modeC_graph_ci_cpu`. Would you be able to investigate this please?
> 
> Also, do you have any measurements of the speedup of this optimization?
[Eltwise_results.xlxs.pdf](https://github.com/user-attachments/files/16925709/Eltwise_results.xlxs.pdf)

2024-09-09 10:53 UTC, jondea approved these changes
Thanks for the logs and numbers, they are really useful. I ran this on a Graviton 3, and there was no effect on performance. Just to check: this is what you expected? I'm guessing this because the bulk of the added code is guarded by SVE length == 512.

But, given that you got a ~5x speedup, I was curious if this optimization could be applied to the Graviton 3, so I removed the check and measured the performance. Surprisingly, I got ~1.5x slowdown on Graviton 3. I don't think this should block this PR because you have added the guard, but it is surprising. Could it be that `exp_compute_vector_fwd` is slower than it could be for some reason for SVE 512?

Anyways, in summary, I'm happy to approve once you've investigated the extra unit test failures.

2024-09-09 10:54 UTC, jondea requested changes
Sorry, accidentally approved

2024-09-09 11:15 UTC, nikhilfujitsu commented
> Thanks for the logs and numbers, they are really useful. I ran this on a Graviton 3, and there was no effect on performance. Just to check: this is what you expected? I'm guessing this because the bulk of the added code is guarded by SVE length == 512.
> 
> But, given that you got a ~5x speedup, I was curious if this optimization could be applied to the Graviton 3, so I removed the check and measured the performance. Surprisingly, I got ~1.5x slowdown on Graviton 3. I don't think this should block this PR because you have added the guard, but it is surprising. Could it be that `exp_compute_vector_fwd` is slower than it could be for some reason for SVE 512?
> 
> Anyways, in summary, I'm happy to approve once you've investigated the extra unit test failures.

It is true that we get 1.5x slowdown on G3 machines( SVE_256). That's why it is limited to SVE_512.

Extra unit cases are failing on SVE_512 machines already in the main branch. 
By adding my changes no effect is there on failed test cases. The failed test cases are for SVE_512 machine not for Graviton or SVE_256 machine. If this helps.

2024-09-09 13:30 UTC, nikhilfujitsu commented
> > Thanks for the logs and numbers, they are really useful. I ran this on a Graviton 3, and there was no effect on performance. Just to check: this is what you expected? I'm guessing this because the bulk of the added code is guarded by SVE length == 512.
> > But, given that you got a ~5x speedup, I was curious if this optimization could be applied to the Graviton 3, so I removed the check and measured the performance. Surprisingly, I got ~1.5x slowdown on Graviton 3. I don't think this should block this PR because you have added the guard, but it is surprising. Could it be that `exp_compute_vector_fwd` is slower than it could be for some reason for SVE 512?
> > Anyways, in summary, I'm happy to approve once you've investigated the extra unit test failures.
> 
> It is true that we get 1.5x slowdown on G3 machines( SVE_256). That's why it is limited to SVE_512.
> 
> Extra unit cases are failing on SVE_512 machines already in the main branch. By adding my changes no effect is there on failed test cases. The failed test cases are for SVE_512 machine not for Graviton or SVE_256 machine. If this helps.

I am also checking with latest changes in main. Will update you soon.

2024-09-09 16:05 UTC, nikhilfujitsu commented
> > > Thanks for the logs and numbers, they are really useful. I ran this on a Graviton 3, and there was no effect on performance. Just to check: this is what you expected? I'm guessing this because the bulk of the added code is guarded by SVE length == 512.
> > > But, given that you got a ~5x speedup, I was curious if this optimization could be applied to the Graviton 3, so I removed the check and measured the performance. Surprisingly, I got ~1.5x slowdown on Graviton 3. I don't think this should block this PR because you have added the guard, but it is surprising. Could it be that `exp_compute_vector_fwd` is slower than it could be for some reason for SVE 512?
> > > Anyways, in summary, I'm happy to approve once you've investigated the extra unit test failures.
> > 
> > 
> > It is true that we get 1.5x slowdown on G3 machines( SVE_256). That's why it is limited to SVE_512.
> > Extra unit cases are failing on SVE_512 machines already in the main branch. By adding my changes no effect is there on failed test cases. The failed test cases are for SVE_512 machine not for Graviton or SVE_256 machine. If this helps.
> 
> I am also checking with latest changes in main. Will update you soon.

@jondea After merging latest changes from main, errors are resolved. So I have updated the description also. Please consider approval. Thanks.

2024-09-09 16:08 UTC, vpirogov commented
@nikhilfujitsu, merge commits are not allowed in production branches. Please rebase your changes.

2024-09-09 17:07 UTC, nikhilfujitsu commented
> @nikhilfujitsu, merge commits are not allowed in production branches. Please rebase your changes.

Hi I am struggling to get this rebased again could you please help me here.
What I did is. 
I pressed the sync fork button which merged the main branch changes with my branch.
Now how can I rebase it and push it back here.
Should I revert my merge first then rebase it?

2024-09-09 17:22 UTC, vpirogov commented
> Hi I am struggling to get this rebased again could you please help me here.

This operation can be done from console:
```
git checkout gelu_erf
git rebase main
git push --force
```

2024-09-10 02:29 UTC, nikhilfujitsu commented
> > Hi I am struggling to get this rebased again could you please help me here.
> 
> This operation can be done from console:
> 
> ```
> git checkout gelu_erf
> git rebase main
> git push --force
> ```

Thank you. Means a lot to me.

2024-09-10 06:56 UTC, nikhilfujitsu commented
> > > Hi I am struggling to get this rebased again could you please help me here.
> > 
> > 
> > This operation can be done from console:
> > ```
> > git checkout gelu_erf
> > git rebase main
> > git push --force
> > ```
> 
> Thank you. Means a lot to me.

@jondea @vpirogov Please approve the changes. ThankYou.

2024-09-10 16:30 UTC, nikhilfujitsu reviewed
Changes Reviewed. And description changed accordingly.

2024-09-16 07:50 UTC, abhijain1204fujitsu commented
@jondea @vpirogov could you please support to check the changes as per feedback received.

2024-09-16 13:10 UTC, jondea approved these changes

2024-09-20 05:17 UTC, abhijain1204fujitsu commented
@vpirogov Kindly let us know if any other change is required
Kindly support for merger.

2024-09-23 02:54 UTC, nikhilfujitsu commented
> @vpirogov Kindly let us know if any other change is required Kindly support for merger.

Dear @vpirogov please approve the merger or let us know for any other changes.

2024-10-02 17:05 UTC, theComputeKid commented
Can you please rebase your changes so it triggers the aarch64 pipeline we have added since? Thanks.

2024-10-02 17:06 UTC, theComputeKid requested changes
Will approve after CI passes on rebase.

2024-10-03 08:19 UTC, nikhilfujitsu commented
@theComputeKid  Hi, thanks for the comment. I have rebased the branch.

2024-10-03 10:41 UTC, theComputeKid approved these changes
Thanks!

2024-10-03 18:08 UTC, merged