build: cmake: unsupported compilers cleanup
oneapi-src/oneDNN pull request #2296
Opened 2024-12-19 18:13 UTC by spalicki

Build files and documentation cleanup to remove dependencies and hacks for GCC < 8 and Clang < 11.

2024-12-19 20:08 UTC, vpirogov commented
The main driver for this change is cleaning up old workarounds for compiler bugs from codebase and compiler version checks from the build system. The change is driven by RHEL 7 reaching end of support and new versions allow oneDNN to build on RHEL 8 out of the box.

2024-12-20 14:43 UTC, theComputeKid commented
AArch64 validation is outdated, it is now on ubuntu 22.04 with gcc-10, gcc-13 and clang-17

MacOS-14 is also run in the CI.

2024-12-20 18:40 UTC, spalicki commented
@theComputeKid I have updated the README entries for AArch64 based on #2294 and what you posted here.

2024-12-20 18:45 UTC, theComputeKid requested changes

2024-12-20 18:45 UTC, theComputeKid commented on README.md
> +* GNU Compiler Collection 10, 13 and 17
10, 13

There is no gcc-17

2024-12-20 18:47 UTC, theComputeKid commented
Is this a draft or would you like me to review?

2024-12-20 18:52 UTC, spalicki commented on README.md
> +* GNU Compiler Collection 10, 13 and 17
Clang 17, sorry for that.

2024-12-24 14:42 UTC, theComputeKid approved these changes
AArch64 looks good to me. I'm always tweaking CI (Arm runners are still new) so if anything changes, I'll change it here too.

2024-12-30 18:21 UTC, spalicki commented
@dmitry-gorokhov, @ilya-lavrenov, @vladimir-paramuzov I looked through [OpenVINO build documentation](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build_linux.md), and it specifies that the lowest supported OS is Ubuntu 18.04 and GCC 7.5.0. [Release documentation](https://docs.openvino.ai/2024/about-openvino/release-notes-openvino/system-requirements.html) does not have these dependencies and starts at Ubuntu 20.04 (and I assume GCC 8.5.0) but at the same time shows CentOS 7. Which one is correct?

2024-12-30 19:39 UTC, ilya-lavrenov commented
Ubuntu 20.04 is minimal
CentOS 7 is supported with non default compiler (we use manylinux docker image with gcc-10)
We also support RHEL 8.4 with gcc 8.5

2024-12-31 17:41 UTC, vpirogov commented
There are some outdated compiler version checks in the implementation:
* [src/common/compiler_workarounds.hpp](https://github.com/oneapi-src/oneDNN/blob/main/src/common/compiler_workarounds.hpp)
* [src/cpu/x64/jit_uni_xf16_sum.cpp#L439](https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/jit_uni_xf16_sum.cpp#L439)
* [src/common/dnnl_thread.hpp#L197](https://github.com/oneapi-src/oneDNN/blob/main/src/common/dnnl_thread.hpp#L197)

I would not touch third party components like Xbyak, spdlog and gtest.

2025-01-02 21:01 UTC, spalicki commented
make test

2025-01-03 18:08 UTC, dzarukin approved these changes

2025-01-03 18:08 UTC, dzarukin commented on cmake/coverage.cmake
> +    if(CMAKE_CXX_COMPILER_ID MATCHES "(Apple)?[Cc]lang|GNU")
?
```suggestion
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "(Apple)?[Cc]lang|GNU")
```

2025-01-03 18:46 UTC, densamoilov approved these changes

2025-01-03 18:55 UTC, vpirogov approved these changes

2025-01-06 19:13 UTC, spalicki commented on src/common/compiler_workarounds.hpp
>  #define CLANG_WA_02_SAFE_TO_USE_OMP_SIMD 1
I will extend this to remove it for version where it was fixed - definitely 14, but I need to check 13.

2025-01-06 20:06 UTC, dzarukin commented on src/common/compiler_workarounds.hpp
I have it removed in https://github.com/oneapi-src/oneDNN/pull/2270, shouldn't be an issue.

2025-01-06 20:31 UTC, spalicki commented
make test

2025-01-07 01:45 UTC, TaoLv approved these changes

2025-01-07 05:14 UTC, merged