cpu: aarch64: add JIT implementation for softmax
oneapi-src/oneDNN pull request #949
Opened 2021-01-15 04:28 UTC by kawakami-k

# Description

This PR adds JIT support of softmax for AArch64.
It includes JIT implementation for SVE 512.
 [Related RFC#841](https://github.com/oneapi-src/oneDNN/pull/841) 
 [Related PR#850](https://github.com/oneapi-src/oneDNN/pull/850)

# Checklist

## Code-change submissions

- [x] Do all unit and benchdnn tests (`make test` and `make test_benchdnn_*`) pass locally?
- [x] Have you formatted the code using clang-format?

### New features

- [N/A] Have you added relevant tests?
- [N/A] Have you provided motivation for adding a new feature?

There is no need to add a new tests for this PR, 
since we can use the existing gtests and benchdnn for this PR.

2021-01-28 18:25 UTC, mgouicem requested changes
Note that we recently changed the behavior of how memory padding is zero initilized.
It used to happen upon `set_data_handle` call, now all primitive are responsible to properly zero pad their outputs. See [this RFC](https://github.com/oneapi-src/oneDNN/tree/rfcs/rfcs/20201119-change-memory-init-behavior), option 1 for more details.

2021-01-28 18:25 UTC, mgouicem commented on src/cpu/aarch64/jit_uni_softmax.cpp
> +    auto dst = CTX_OUT_MEM(char *, DNNL_ARG_DST);
please use `CTX_OUT_CLEAN_MEM` to enforce zero padding of the output.

2021-01-28 18:25 UTC, mgouicem commented on src/cpu/aarch64/jit_uni_softmax.cpp
> +    auto diff_src = CTX_OUT_MEM(char *, DNNL_ARG_DIFF_SRC);
same here, please use `CTX_OUT_CLEAN_MEM`

2021-01-29 04:26 UTC, kawakami-k commented
Hi, @mgouicem, I modified this PR as you've suggested. I confirmed all `gtests` and `benchdnn` PASSed, if `cpu/aarch64/jit_sve_512_conv_kernel.cpp` is fixed, which is being disscussed at #965.

2021-01-29 19:27 UTC, mgouicem approved these changes
Looks good to me, thanks!

2021-02-02 04:18 UTC, merged